baseURL: 'https://chocole.top/'
buildDrafts: true
languageCode: en-us
title: "Random Notes"
module:
  imports:
    - path: github.com/adityatelange/hugo-PaperMod
markup:
  goldmark:
    renderer:
      unsafe: true

Params:
  env: production
  homeInfoParams:
    Title: "Cole's Random Notes"
    # Content: "Github: @Sduby22"
  socialIcons:
    - name: "github"
      url: "https://github.com/Sduby22"
  ShowBreadCrumbs: true
  ShowReadingTime: true
  ShowPostNavLinks: true
  ShowCodeCopyButtons: true
  ShowToc: true

outputs:
  home:
    - HTML
    - RSS
    - JSON

menu:
  main:
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 20
    - identifier: search
      name: Search
      url: /search/
      weight: 20
    - identifier: archives
      name: Archives
      url: /archives/
      weight: 20
