baseURL: 'sduby22.github.io/blog/'
languageCode: en-us
title: My New Hugo Site
module:
  imports:
    - path: github.com/adityatelange/hugo-PaperMod
markup:
  goldmark:
    renderer:
      unsafe: true

Params:
  env: production
  homeInfoParams:
    Title: Hi there wave
    Content: Can be Info, links, about...
  ShowBreadCrumbs: true
  ShowReadingTime: true
  ShowPostNavLinks: true
  ShowCodeCopyButtons: true
  ShowToc: true

outputs:
  home:
    - HTML
    - RSS
    - JSON

menu:
  main:
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 20
    - identifier: search
      name: Search
      url: /search/
      weight: 20
